# Chapter 12: Demo Hierarchy Clustering

In [1]:
import matplotlib.pyplot as plt  
import pandas as pd  
%matplotlib inline
import numpy as np  

In [2]:
X = np.array([[5,3],  
    [10,15],
    [15,12],
    [24,10],
    [85, 90],         
    [30,30],
    [85,70],
    [71,80],
    [60,78],
    [70,55],
    [80,91],])

In [ ]:
import scipy.cluster.hierarchy as shc
plt.figure(figsize=(10, 3))
plt.title("Dendograms")  
dend = shc.dendrogram(shc.linkage(X, method='ward')) 

In [3]:
# cluster = 2 
from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=2, affinity='euclidean') 
cluster.fit(X) # Fit the hierarchical clustering on the data

AgglomerativeClustering()

In [4]:
print(cluster.labels_)  

[1 1 1 1 0 1 0 0 0 0 0]


In [5]:
X_test = np.array([[65,75], [75,85]])
plt.scatter(X[:,0],X[:,1], c=cluster.labels_, cmap='rainbow')  

In [ ]:
cluster.fit_predict(X) 

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0])

In [ ]:
X_test = np.array([[65,75], [35,40]])
cluster.fit_predict(X_test)

array([1, 0])